/**
 * Evaluates a target rule formula against intake answers.
 * All targets are computed here — never generated by AI.
 */
function evaluateTargets(targetRules, intakeAnswers) {
  const results = {};
  for (const rule of targetRules) {
    // Build a safe evaluation context from intake answers
    const context = { ...intakeAnswers };
    // Evaluate formula using only the context variables
    try {
      const fn = new Function(...Object.keys(context), `return ${rule.formula};`);
      const value = fn(...Object.values(context));
      const rounded = Math.round(value * 10) / 10;
      results[rule.metric] = {
        value: rounded,
        display: rule.display.replace('{value}', rounded),
        ruleId: rule.id,
      };
    } catch {
      results[rule.metric] = { value: null, display: rule.display, ruleId: rule.id };
    }
  }
  return results;
}

/**
 * Determines if a goal is working based on baseline, current value, and evaluation rule.
 */
function evaluateProgress(baseline, current, evaluationRule) {
  const delta = current - baseline;
  const { direction, minChangeToFlagWorking } = evaluationRule;

  if (direction === 'increase') {
    return { delta, isWorking: delta >= minChangeToFlagWorking };
  } else {
    return { delta, isWorking: delta <= -minChangeToFlagWorking };
  }
}

/**
 * Safety guardrail: rejects unsafe fat loss targets.
 */
function validateSafety(goalId, intakeAnswers, targets) {
  if (goalId === 'fat_loss') {
    const { bodyweight_kg, goal_weight_kg } = intakeAnswers;
    if (goal_weight_kg && bodyweight_kg) {
      const totalLoss = bodyweight_kg - goal_weight_kg;
      if (totalLoss > bodyweight_kg * 0.2) {
        return {
          safe: false,
          message: 'Your goal weight implies a large change. Please consult a healthcare professional before starting.',
        };
      }
    }
  }
  return { safe: true };
}

module.exports = { evaluateTargets, evaluateProgress, validateSafety };
